In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import numpy as np

In [ ]:

movies = pd.read_csv("movies.txt", on_bad_lines='skip', sep = ';', header = None)

In [ ]:
movies = movies.iloc[1: , :]

In [ ]:
movies

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
1,Incredibles 2,Avengers: Infinity War - Part I,Avengers: Infinity War - Part II,Deadpool 2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Annihilation,John Wick: Chapter 3 – Parabellum,Deadpool 2,Incredibles 2,Avengers: Infinity War - Part I,Avengers: Infinity War - Part II,Mission: Impossible - Fallout,Spider-Man: Into the Spider-Verse,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Avengers: Infinity War - Part I,Bohemian Rhapsody,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Green Book,Incredibles 2,Isle of Dogs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Bohemian Rhapsody,Captain Marvel,Avengers: Infinity War - Part I,Spider-Man: Into the Spider-Verse,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8888,Incredibles 2,Isle of Dogs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8889,Free Solo,Deadpool 2,Green Book,Incredibles 2,Won't You Be My Neighbor?,Avengers: Infinity War - Part I,Shazam!,Bohemian Rhapsody,Avengers: Infinity War - Part II,Isle of Dogs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8890,Green Book,Avengers: Infinity War - Part I,Avengers: Infinity War - Part II,Game Night,Annihilation,The Cloverfield Paradox,Hereditary,Black Mirror: Bandersnatch,Eighth Grade,Captain Marvel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8891,Annihilation,Roma,BlacKkKlansman,Deadpool 2,Tomb Raider,A Quiet Place,First Man,The Ballad of Buster Scruggs,Sorry to Bother You,Game Night,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8892,Once Upon a Time in Hollywood,Avengers: Infinity War - Part II,Joker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

mv = []
for i in range(0, movies.shape[0]):
  for j in range(0, movies.shape[1]):
    mv.append(movies.values[i, j])
mv = np.array(mv)

In [ ]:
mv_df = pd.DataFrame(mv, columns = ['title'])

mv_df['rate count'] = 1

In [ ]:
indexNames = mv_df[mv_df['title'] == 'nan'].index
mv_df.drop(indexNames, inplace = True)

In [ ]:
df_table = mv_df.groupby('title').sum().sort_values('rate count', ascending = False).reset_index()

In [ ]:
df_table.head(10).style.background_gradient(cmap='Blues')

In [ ]:
conv = []
for i in range(movies.shape[0]):
  conv.append([str(movies.values[i, j]) for j in range(movies.shape[1])])

conv = np.array(conv)

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import matplotlib.pyplot as plt


conv_te = TransactionEncoder()

In [ ]:
conv_te_ary = conv_te.fit(conv).transform(conv)
dataset = pd.DataFrame(conv_te_ary, columns = conv_te.columns_)

In [ ]:
def encode_units(x):
  if x == False:
    return 0
  if x == True:
    return 1
  
dataset = dataset.applymap(encode_units)

In [ ]:
dataset = dataset.iloc[: , :-1]
dataset

,A Quiet Place,A Star Is Born,Alita: Battle Angel,Annihilation,Ant-Man and the Wasp,Aquaman,Avengers: Infinity War - Part I,Avengers: Infinity War - Part II,Bad Times at the El Royale,Bird Box,...,Sorry to Bother You,Spider-Man: Far from Home,Spider-Man: Into the Spider-Verse,The Ballad of Buster Scruggs,The Cloverfield Paradox,Tomb Raider,Upgrade,Us,Venom,Won't You Be My Neighbor?
0,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8887,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8888,0,0,0,0,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
8889,1,0,0,1,1,0,1,1,0,1,...,0,0,1,0,1,1,0,0,0,0
8890,1,0,0,1,0,0,0,0,0,0,...,1,0,0,1,0,1,1,0,0,0
8891,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
frequent_movies = apriori(dataset, min_support = 0.05, use_colnames = True)

In [ ]:
frequent_movies['length'] = frequent_movies['itemsets'].apply(lambda x: len(x))

In [ ]:
rules = association_rules(frequent_movies, metric = 'lift', min_threshold = 1.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(A Quiet Place),(A Star Is Born),0.247638,0.113923,0.054543,0.220254,1.933368,0.026332,1.136367
1,(A Star Is Born),(A Quiet Place),0.113923,0.247638,0.054543,0.478776,1.933368,0.026332,1.443451
2,(A Quiet Place),(Annihilation),0.247638,0.215475,0.117296,0.473660,2.198219,0.063937,1.490531
3,(Annihilation),(A Quiet Place),0.215475,0.247638,0.117296,0.544363,2.198219,0.063937,1.651231
4,(A Quiet Place),(Ant-Man and the Wasp),0.247638,0.205353,0.080184,0.323797,1.576779,0.029331,1.175159
...,...,...,...,...,...,...,...,...,...
3499,(Deadpool 2),"(Spider-Man: Far from Home, Avengers: Infinity...",0.450180,0.079285,0.059829,0.132900,1.676241,0.024137,1.061833
3500,(Avengers: Infinity War - Part II),"(Deadpool 2, Avengers: Infinity War - Part I, ...",0.311628,0.061066,0.059829,0.191988,3.143943,0.040799,1.162030
3501,(Spider-Man: Far from Home),"(Deadpool 2, Avengers: Infinity War - Part I, ...",0.127081,0.105601,0.059829,0.470796,4.458277,0.046409,1.690086
3502,(Avengers: Infinity War - Part I),"(Deadpool 2, Avengers: Infinity War - Part II,...",0.595367,0.062416,0.059829,0.100491,1.610031,0.022669,1.042329
3503,(Spider-Man: Into the Spider-Verse),"(Deadpool 2, Avengers: Infinity War - Part I, ...",0.334683,0.073999,0.059829,0.178763,2.415752,0.035063,1.127569

In [ ]:
rules['antecedents_length'] = rules['antecedents'].apply(lambda x: len(x))
rules['consequents_length'] = rules['consequents'].apply(lambda x: len(x))
rules.sort_values('lift', ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedents_length,consequents_length
3091,"(Captain Marvel, Avengers: Infinity War - Part...","(Spider-Man: Far from Home, Ant-Man and the Wasp)",0.112236,0.067589,0.051057,0.454910,6.730546,0.043471,1.710563,3,2
3106,"(Spider-Man: Far from Home, Ant-Man and the Wasp)","(Captain Marvel, Avengers: Infinity War - Part...",0.067589,0.112236,0.051057,0.755408,6.730546,0.043471,3.629567,2,3
3098,"(Spider-Man: Far from Home, Avengers: Infinity...","(Captain Marvel, Avengers: Infinity War - Part...",0.065002,0.118983,0.051057,0.785467,6.601487,0.043323,4.106674,3,2
3099,"(Captain Marvel, Avengers: Infinity War - Part...","(Spider-Man: Far from Home, Avengers: Infinity...",0.118983,0.065002,0.051057,0.429112,6.601487,0.043323,1.637794,2,3
3101,"(Captain Marvel, Spider-Man: Far from Home)","(Avengers: Infinity War - Part I, Avengers: In...",0.066914,0.116959,0.051057,0.763025,6.523866,0.043231,3.726307,2,3
...,...,...,...,...,...,...,...,...,...,...,...
200,(Deadpool 2),(BlacKkKlansman),0.450180,0.136640,0.074112,0.164627,1.204822,0.012599,1.033502,1,1
74,(Annihilation),(Spider-Man: Into the Spider-Verse),0.215475,0.334683,0.086820,0.402923,1.203894,0.014704,1.114290,1,1
75,(Spider-Man: Into the Spider-Verse),(Annihilation),0.334683,0.215475,0.086820,0.259409,1.203894,0.014704,1.059323,1,1
217,(Incredibles 2),(Bohemian Rhapsody),0.306905,0.230769,0.085245,0.277757,1.203615,0.014421,1.065059,1,1
216,(Bohemian Rhapsody),(Incredibles 2),0.230769,0.306905,0.085245,0.369396,1.203615,0.014421,1.099096,1,1